# Generated by Django 3.1.2 on 2020-10-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateField(blank=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('Location', models.CharField(choices=[('Corporate Headoffice', 'Corporate Headoffice'), ('Operations Department', 'Operations Department'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], max_length=200, null=True)),
                ('incident_location', models.TextField(max_length=200)),
                ('initial_Severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], max_length=200, null=True)),
                ('Immedate_Action_Taken', models.TextField(max_length=200)),
            ],
        ),
    ]
