# Generated by Django 3.1.2 on 2020-10-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='time_date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='timestamp',
        ),
    ]
