# Generated by Django 3.1.2 on 2020-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201007_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Reported_By',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
